### ISSUE TITLE
Time provider override

### ISSUE THREAD

**Issue by k-u-s** [fintermobilityas/snapx#158]
**Is your feature request related to a problem? Please describe.**
Ci that I am using does not allow connection to time.cloudflare.com:123 and I do not have control over it to enable it. 
What causes pack command to fail.

**Describe the solution you'd like**
Allow to specify to use local time instead via cmd args for eg: --time-provider local

**Describe alternatives you've considered**
Configuring CI machine before running pack to re route via all traffic via some proxy.

**Additional context**
Ci screenshot
![image](https://user-images.githubusercontent.com/7735824/113116027-55675e80-920d-11eb-8a0a-c85213b3a5a2.png)

**Comment by peters** [comment]
@k-u-s You can now use a different NTP server by using the following cli argument: --ntp-server time.myserver.com:123

**Comment by k-u-s** [comment]
From which version? I do not see that in list parameters in version 3.0.11 

![image](https://user-images.githubusercontent.com/7735824/113262069-7a70d580-92d0-11eb-89de-d332a404f848.png)

But still does not resolve my issue entirely cause this would require to install ntp server on deploy machine.

**Comment by peters** [comment]
You need to install the newest prerelease:

`dotnet tool update snapx -g --version 4.0.0-prerelease0008`
